In [32]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv("report-deep.csv")
df.head(5)

deep
0   157
1   148
2   149
3   146
4   144

In [33]:
deep = df["deep"]
deep[:10]

0    157
1    148
2    149
3    146
4    144
5    145
6    162
7    163
8    164
9    166
Name: deep, dtype: int64

In [15]:
v_ant = deep[0]
contador_aumento = 0
for p in deep[1:]:
    #esta subiendo la profundidad
    if p > v_ant:
        contador_aumento+=1
    v_ant = p
contador_aumento   

1548

In [17]:
deep = [199,
200,
208,
210,
200,
207,
240,
269,
260,
263]

In [18]:
df.shape

(2000, 1)

### nuevo problema

In [34]:
lista_aux = []
limite = len(deep) - 2
for indice in range(limite):#deep[:len(deep)-2]:
    l = deep[indice:indice+3]
    lista_aux.append(sum(l))
    #print(l)
lista_aux

[454,
 443,
 439,
 435,
 451,
 470,
 489,
 493,
 503,
 525,
 542,
 533,
 515,
 507,
 519,
 523,
 518,
 525,
 549,
 583,
 616,
 644,
 665,
 677,
 684,
 674,
 664,
 658,
 672,
 684,
 691,
 700,
 707,
 715,
 738,
 764,
 786,
 782,
 789,
 805,
 827,
 837,
 843,
 863,
 883,
 910,
 923,
 934,
 935,
 949,
 965,
 979,
 989,
 1000,
 1018,
 1032,
 1045,
 1053,
 1057,
 1079,
 1103,
 1131,
 1141,
 1146,
 1154,
 1167,
 1186,
 1204,
 1229,
 1251,
 1266,
 1273,
 1282,
 1291,
 1307,
 1313,
 1319,
 1333,
 1323,
 1298,
 1263,
 1261,
 1274,
 1275,
 1278,
 1295,
 1317,
 1348,
 1370,
 1402,
 1425,
 1445,
 1465,
 1505,
 1548,
 1585,
 1599,
 1599,
 1571,
 1560,
 1558,
 1579,
 1577,
 1578,
 1574,
 1576,
 1581,
 1591,
 1618,
 1637,
 1664,
 1675,
 1686,
 1693,
 1705,
 1720,
 1739,
 1752,
 1768,
 1775,
 1784,
 1791,
 1802,
 1812,
 1827,
 1833,
 1843,
 1846,
 1857,
 1884,
 1912,
 1924,
 1911,
 1900,
 1899,
 1904,
 1910,
 1920,
 1928,
 1932,
 1930,
 1945,
 1961,
 1979,
 1980,
 2002,
 2038,
 2074,
 2095,
 2105,
 21

In [35]:
deep = lista_aux
v_ant = deep[0]
contador_aumento = 0
for p in deep[1:]:
    #esta subiendo la profundidad
    if p > v_ant:
        contador_aumento+=1
    v_ant = p
contador_aumento  

1589

### Dia 2

#### problema 1

In [39]:
df = pd.read_csv("mov-submarino.csv", sep=" ")
df.head()

mov  incremento
0  forward           2
1     down           2
2  forward           6
3  forward           8
4     down           8

In [28]:
df.groupby(["mov"])["mov"].count()

mov
down       370
forward    405
up         225
Name: mov, dtype: int64

In [29]:
grupo = df.groupby(["mov"]).sum()
grupo

incremento
mov                
down           1810
forward        2034
up             1108

In [30]:
down = grupo["incremento"]["down"]
up = grupo["incremento"]["up"]
forward = grupo["incremento"]["forward"]

In [31]:
forward*(down-up)

1427868

### problema 2

In [40]:
v_depth = 0
v_forward = 0
r_depth =0
for i in range(df.shape[0]):
    r = df.iloc[i]
    if r["mov"] == "down":
        v_depth+= r["incremento"]
    if r["mov"] == "up":
        v_depth-= r["incremento"]
        
    if r["mov"] == "forward":
        v_forward+= r["incremento"]
        r_depth+= r["incremento"]*v_depth
v_depth,v_forward,r_depth

(702, 2034, 770963)

In [41]:
r_depth*v_forward

1568138742

### Dia 3

### problema 1

In [211]:
df = pd.read_csv("noise.csv", dtype={"report": str})
df.head()

report
0  000001110001
1  000001111101
2  010011000000
3  000000000011
4  010000100111

In [212]:
df.shape

(1000, 1)

In [150]:
frecuencia = {x: {0:0, 1:0} for x in range(len(df["report"].iloc[0]))}

for cadena in df["report"]:
    for i in range(len(cadena)):
        frecuencia[i][int(cadena[i])]+=1

In [151]:
frecuencia

{0: {0: 508, 1: 492},
 1: {0: 493, 1: 507},
 2: {0: 499, 1: 501},
 3: {0: 506, 1: 494},
 4: {0: 492, 1: 508},
 5: {0: 492, 1: 508},
 6: {0: 473, 1: 527},
 7: {0: 494, 1: 506},
 8: {0: 505, 1: 495},
 9: {0: 503, 1: 497},
 10: {0: 514, 1: 486},
 11: {0: 514, 1: 486}}

In [166]:
cadena1 = ""
cadena2 = ""
for i in frecuencia:
    cadena1+="1" if frecuencia[i][1]>frecuencia[i][0] else "0"
    cadena2+="1" if frecuencia[i][1]<frecuencia[i][0] else "0"
cadena1, cadena2

('011011110000', '100100001111')

In [167]:
gamma_rate=int(cadena1 ,2)

In [168]:
epsilon_rate =int(cadena2 ,2)

In [169]:
epsilon_rate*gamma_rate

4118544

### problema 2

In [213]:
columnas = np.arange(len(df["report"].iloc[0]))
columnas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [214]:
df2 = pd.DataFrame({}, columns = columnas)
for cadena in df["report"]:
    df2.loc[df2.shape[0]] = [x for x in cadena]

In [215]:
df2

0  1  2  3  4  5  6  7  8  9  10 11
0    0  0  0  0  0  1  1  1  0  0  0  1
1    0  0  0  0  0  1  1  1  1  1  0  1
2    0  1  0  0  1  1  0  0  0  0  0  0
3    0  0  0  0  0  0  0  0  0  0  1  1
4    0  1  0  0  0  0  1  0  0  1  1  1
..  .. .. .. .. .. .. .. .. .. .. .. ..
995  1  0  0  1  1  0  1  0  0  1  0  1
996  1  0  1  0  0  0  0  1  0  1  0  0
997  1  0  0  0  1  1  0  0  0  0  0  0
998  0  0  1  1  1  0  1  0  0  1  0  0
999  1  1  0  0  0  0  1  1  0  0  0  1

[1000 rows x 12 columns]

In [219]:
df3 = df2
for i in columnas:
    if df3.shape[0]>2:
        r = df3[i].value_counts()
        if r[0] == r[1]:
                print(f"misma cantidad {i}")
                df3 = df3[df3[i]=='1']
        else:
                df3 = df3[df3[i]==r.idxmax()]
    else:
        df_aux = df3[df3[i]=='1']
        if df_aux.shape[0]>0:
            df3 = df_aux
    if df3.shape[0] == 1:
        break
df3

misma cantidad 7


0  1  2  3  4  5  6  7  8  9  10 11
48  0  1  0  1  1  1  1  1  0  1  1  1

In [220]:
cadena1= "".join(list(df3.iloc[0]))
cadena1

'010111110111'

In [204]:
'010111100111'

'010111100111'

In [221]:
gamma_rate=int(cadena1 ,2)
gamma_rate

1527

In [223]:
df3 = df2
for i in columnas:
    if df3.shape[0]>2:
        #df3 = df3[df3[i]==df3[i].value_counts().idxmin()]
        r = df3[i].value_counts()
        if r[0] == r[1]:
                df3 = df3[df3[i]=='0']
                print(f"misma cantidad {i}")
        else:
                df3 = df3[df3[i]==r.idxmin()]
        print(df3.shape[0])
    else:
        df_aux = df3[df3[i]=='0']
        if df_aux.shape[0]>0:
            df3 = df_aux
    if df3.shape[0] == 1:
        break
df3

492
240
112
53
23
10
2


0  1  2  3  4  5  6  7  8  9  10 11
61  1  0  0  1  1  1  0  0  1  1  1  0

In [224]:
cadena2= "".join(list(df3.iloc[0]))
cadena2

'100111001110'

In [225]:
100111001110

100111001110

In [226]:
epsilon_rate=int(cadena2 ,2)
epsilon_rate

2510

In [ ]:
2510

In [227]:
epsilon_rate*gamma_rate

3832770

In [136]:
i = 1
df3 = df3[df3[i]==df3[i].value_counts().idxmin()]
df3

0  1  2  3  4
5   0  1  1  1  1
11  0  1  0  1  0

In [191]:
df3 = df2

In [192]:
df3[i].value_counts()

0    514
1    486
Name: 11, dtype: int64

In [193]:
r = df3[i].value_counts()

In [194]:
r

0    514
1    486
Name: 11, dtype: int64

In [195]:
r[0]

514

### Dia 4

### problema 1

In [199]:
f = open("bingo.txt", "r")
raw = f.read()

In [200]:
l = raw.split("\n") 
l[:4]

['31,88,35,24,46,48,95,42,18,43,71,32,92,62,97,63,50,2,60,58,74,66,15,87,57,34,14,3,54,93,75,22,45,10,56,12,83,30,8,76,1,78,82,39,98,37,19,26,81,64,55,41,16,4,72,5,52,80,84,67,21,86,23,91,0,68,36,13,44,20,69,40,90,96,27,77,38,49,94,47,9,65,28,59,79,6,29,61,53,11,17,73,99,25,89,51,7,33,85,70',
 '',
 '50 83  3 31 16',
 '47  9 94 10 86']

In [201]:
lista_sorteo = np.fromstring(l[0], sep = ',', dtype= int)
lista_sorteo[:10]

array([31, 88, 35, 24, 46, 48, 95, 42, 18, 43])

In [202]:
tableros_raw = l[1:]
tableros_raw

['',
 '50 83  3 31 16',
 '47  9 94 10 86',
 '61 22 53 46 74',
 '77 41 79 55 62',
 '97 78 43 73 40',
 '',
 '99 96 20 35 21',
 '38 17 48 69 68',
 ' 9 51 32 52 11',
 '67  8 42 89 27',
 '39 62 66 72 43',
 '',
 '33 16  4 78 31',
 '96 66 13 55 18',
 '47 89 83 99 85',
 '50 43 39 34 98',
 '81 65  7 23 17',
 '',
 '24 13 57 84 50',
 '83 86 98 92  7',
 '28 31 85 21 12',
 '37 48 43 47 67',
 '19 27  1 20 16',
 '',
 '38 75  3 14  4',
 ' 8 86 98 94 83',
 '60 46 63 85 20',
 '69 26 73 40 29',
 '48 84 33 18 74',
 '',
 '13 33 37 45 22',
 '19 28 61 58 69',
 '42 14 23 39 88',
 '92 81 54 99 52',
 '57  3 34 29 62',
 '',
 '19 71 46 13 81',
 '99 34  8  7 89',
 '72 56 38 22 27',
 '52  2 44 12  4',
 '53 86 45 95 39',
 '',
 '67 12 16 60 47',
 '79 21 99 15 59',
 '81 13 64 83  4',
 '85 48 17 29 66',
 '41 97 80 51 68',
 '',
 '72 19 67  6  9',
 '63 80 78 97 43',
 '53 73 91 44 47',
 ' 3 54 41 61 70',
 '69 36 57 55 45',
 '',
 '97  7 39 48 10',
 '77 42 65 89 79',
 '24 58 23 37 15',
 '26 71 41 18 87',
 '50 88 98 43  1',


In [203]:
while '' in tableros_raw:
    tableros_raw.remove('')
tableros_raw[:5]

['50 83  3 31 16',
 '47  9 94 10 86',
 '61 22 53 46 74',
 '77 41 79 55 62',
 '97 78 43 73 40']

In [179]:
lista_tableros = []
numero_t = int(len(tableros_raw)/5)
numero_t

3

In [180]:
seccion = 0
for i in range(numero_t):
    t1 = np.empty((0, 5), int)
    for fila_raw in tableros_raw[seccion:seccion+5]:
        t1=np.append(t1, [np.fromstring(fila_raw, sep = ' ', dtype= int)], axis=0)
    lista_tableros.append((t1, np.full((5, 5), False, dtype=bool)))
    seccion+=5
lista_tableros

[(array([[22, 13, 17, 11,  0],
         [ 8,  2, 23,  4, 24],
         [21,  9, 14, 16,  7],
         [ 6, 10,  3, 18,  5],
         [ 1, 12, 20, 15, 19]]),
  array([[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]])),
 (array([[ 3, 15,  0,  2, 22],
         [ 9, 18, 13, 17,  5],
         [19,  8,  7, 25, 23],
         [20, 11, 10, 24,  4],
         [14, 21, 16, 12,  6]]),
  array([[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]])),
 (array([[14, 21, 17, 24,  4],
         [10, 16, 15,  9, 19],
         [18,  8, 23, 26, 20],
         [22, 11, 13,  6,  5],
         [ 2,  0, 12,  3,  7]]),
  array([[False, False, False, False, False],
         [False, 

In [98]:
def tableroGanadorColumnaOFila(tablero):
    for i in range(tablero.shape[0]):
        fila = tablero[i]
        columna = tablero[:,i]
        if not False in fila:
            return True
        if not False in columna:
            return True
    return False

In [130]:
def marcarTablero(tablero, tablero_m, valor):
    for i in range(5):
        for j in range(5):
            if tablero[i][j] == valor:
                tablero_m[i][j] = True
                return True
    return False

In [153]:
def calcularPuntosTableros(tablero, tablero_m):
    suma = 0
    for i in range(5):
        for j in range(5):
            if not tablero_m[i][j]:
                suma+=tablero[i][j]
    return suma

In [164]:
lista_tableros[0]

(array([[50, 83,  3, 31, 16],
        [47,  9, 94, 10, 86],
        [61, 22, 53, 46, 74],
        [77, 41, 79, 55, 62],
        [97, 78, 43, 73, 40]]),
 array([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]))

In [132]:
marcarTablero(lista_tableros[0][0], lista_tableros[0][1], 24)

True

In [133]:
lista_tableros[0]

(array([[22, 13, 17, 11,  0],
        [ 8,  2, 23,  4, 24],
        [21,  9, 14, 16,  7],
        [ 6, 10,  3, 18,  5],
        [ 1, 12, 20, 15, 19]]),
 array([[False, False, False, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]))

In [165]:
t_ganador = None
for numero in lista_sorteo:
    for i_table in range(len(lista_tableros)):
        marcarTablero(lista_tableros[i_table][0], 
                     lista_tableros[i_table][1], numero)
        if tableroGanadorColumnaOFila(lista_tableros[i_table][1]):
            t_ganador = i_table
            break
    if t_ganador != None:
        break
t_ganador

66

In [151]:
lista_tableros

[(array([[22, 13, 17, 11,  0],
         [ 8,  2, 23,  4, 24],
         [21,  9, 14, 16,  7],
         [ 6, 10,  3, 18,  5],
         [ 1, 12, 20, 15, 19]]),
  array([[False, False,  True,  True,  True],
         [False,  True,  True,  True,  True],
         [ True,  True,  True, False,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]])),
 (array([[ 3, 15,  0,  2, 22],
         [ 9, 18, 13, 17,  5],
         [19,  8,  7, 25, 23],
         [20, 11, 10, 24,  4],
         [14, 21, 16, 12,  6]]),
  array([[False, False,  True,  True, False],
         [ True, False, False,  True,  True],
         [False, False,  True, False,  True],
         [False,  True, False,  True,  True],
         [ True,  True, False, False, False]])),
 (array([[14, 21, 17, 24,  4],
         [10, 16, 15,  9, 19],
         [18,  8, 23, 26, 20],
         [22, 11, 13,  6,  5],
         [ 2,  0, 12,  3,  7]]),
  array([[ True,  True,  True,  True,  True],
         [False, 

In [166]:
p_tablero= calcularPuntosTableros(lista_tableros[t_ganador][0], lista_tableros[t_ganador][1])
p_tablero

1026

In [167]:
numero

66

In [168]:
p_tablero*numero

67716

### problema 2

3

In [204]:
lista_tableros = []
numero_t = int(len(tableros_raw)/5)
numero_t

seccion = 0
for i in range(numero_t):
    t1 = np.empty((0, 5), int)
    for fila_raw in tableros_raw[seccion:seccion+5]:
        t1=np.append(t1, [np.fromstring(fila_raw, sep = ' ', dtype= int)], axis=0)
    lista_tableros.append((t1, np.full((5, 5), False, dtype=bool)))
    seccion+=5
#lista_tableros

In [205]:
t_ganador = None
lista_ganadores = []
for numero in lista_sorteo:
    for i_table in range(len(lista_tableros)):
        marcarTablero(lista_tableros[i_table][0], 
                     lista_tableros[i_table][1], numero)
        if tableroGanadorColumnaOFila(lista_tableros[i_table][1]):
            t_ganador = i_table
            if not t_ganador in lista_ganadores:
                lista_ganadores.append(t_ganador)
            contador_ganadores+=1
            #break
    if len(lista_tableros) == len(lista_ganadores):
        break
lista_ganadores

[66,
 93,
 43,
 99,
 91,
 51,
 85,
 13,
 55,
 62,
 46,
 54,
 95,
 60,
 81,
 84,
 47,
 88,
 32,
 2,
 9,
 58,
 59,
 22,
 56,
 86,
 71,
 74,
 82,
 90,
 10,
 17,
 38,
 24,
 37,
 79,
 33,
 0,
 18,
 28,
 44,
 76,
 50,
 1,
 15,
 39,
 61,
 25,
 45,
 8,
 68,
 69,
 70,
 96,
 67,
 35,
 89,
 26,
 41,
 4,
 6,
 21,
 29,
 42,
 53,
 65,
 5,
 27,
 36,
 77,
 52,
 34,
 40,
 57,
 87,
 3,
 7,
 20,
 30,
 83,
 16,
 48,
 75,
 19,
 12,
 72,
 97,
 23,
 63,
 80,
 11,
 49,
 94,
 78,
 14,
 92,
 73,
 98,
 64,
 31]

In [206]:
numero

6

In [207]:
t_ganador = lista_ganadores[-1]
t_ganador

31

In [208]:
p_tablero= calcularPuntosTableros(lista_tableros[t_ganador][0], lista_tableros[t_ganador][1])
p_tablero

305

In [209]:
numero*p_tablero

1830